# Z-Test

In [2]:
import math
import numpy as np
import scipy

A school claimed that the students study that is more intelligent than the average school. On calculating the IQ score of 50 students, the average turns out to be 110. The mean of the population IQ is 100 and the standard deviation is 15. State whether the claim of principal is right or not at 5% significance level.

In [3]:
alpha=0.05

In [4]:
import scipy.stats

In [5]:
#Defining z-test function
def ztest(n,sample_mean,pop_mean,pop_sd,alternative):
    z_score=(sample_mean-pop_mean)/(pop_sd/math.sqrt(n))
    #Gives value of p for a given z-score
    p_value = scipy.stats.norm.sf(z_score)
    print(z_score)
    print(p_value)
    if(alternative == "one-sided"):
        if(p_value<alpha):
            print("Reject the null hypothesis")
        else:
            print("Failed to reject the null hypothesis")
    elif(alternative == "two-sided"):
        if(p_value<alpha/2):
            print("Reject the null hypothesis")
        else:
            print("Failed to reject the null hypothesis")

In [6]:
ztest(50,110,100,15,"one-sided")

4.714045207910317
1.2142337364879197e-06
Reject the null hypothesis


A teacher claims that the mean score of students in his class is greater than 82 with the standard deviation of 20. If a sample of 81 students was selected with the eman score of 90 then check if there is enough evidence to support this claim at a 0.05 significance level.


In [7]:
ztest(81,90,82,20,"one-sided")

3.5999999999999996
0.00015910859015753396
Reject the null hypothesis


# T-Test

In [8]:
import numpy as np
from numpy.random import randn
import scipy.stats as stats

A school claimed that the students study that is more intelligent than the average school. On calculating the IQ scores of 30 students, the average turns out to be 140 and standard deviation is 20. The mean of the population IQ is 100. State whether the claim of principal is right or not at 5% significance level

In [9]:
sample_mean=140
sample_std=20
data = sample_std*randn(30)+sample_mean

In [10]:
alpha = 0.05

In [11]:
print(np.mean(data),(np.std(data)))

138.1050803557674 17.92251912272558


In [12]:
#T-Test for 1 sample
t_statistic,pvalue = stats.ttest_1samp(a=data, popmean=100)

In [13]:
if(pvalue<alpha):
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Reject the null hypothesis


# Chi-Square Test

In [14]:
from scipy.stats import chisquare

In [17]:
chi_square,p_value=chisquare([48,24,24]) #Favourible Indifferent Unfavourale

In [18]:
chi_square, p_value

(12.0, 0.002478752176666357)

In [19]:
alpha=0.05

In [20]:
if(p_value<alpha):
    print("Dependent (Reject H0)")
else:
    print("Independent (H0 holds true)")

Dependent (Reject H0)


In [23]:
chisquare2,p_value2=chisquare([5,9,13,7,6])

In [27]:
chisquare2,p_value2

(5.0, 0.2872974951836458)

In [24]:
alpha=0.05

In [26]:
if(p_value2<alpha):
    print("Dependent (reject H0)")
else:
    print("Independent (H0 holds true)")

Independent (H0 holds true)


In [28]:
from scipy.stats import chi2_contingency

In [34]:
#Returs Statistic, p-value, dof, expected value
chi2_contingency([[207,282,241],[234,242,232]]) #Gives the expected frequency

(4.542228269825232,
 0.1031971404730939,
 2,
 array([[223.87343533, 266.00834492, 240.11821975],
        [217.12656467, 257.99165508, 232.88178025]]))

# Chi-Squared Test for Feature Selection

In [35]:
outlook_data=[[2,3],[4,0],[3,2]]

In [36]:
chi2_contingency(outlook_data)

(3.546666666666666,
 0.16976615743981124,
 2,
 array([[3.21428571, 1.78571429],
        [2.57142857, 1.42857143],
        [3.21428571, 1.78571429]]))

In [37]:
wind_data =[[3,3],[6,2]]

In [38]:
chi2_contingency(wind_data)

(0.16203703703703703,
 0.687287949348002,
 1,
 array([[3.85714286, 2.14285714],
        [5.14285714, 2.85714286]]))

In [39]:
obs = [3,3,6,2]
exp = [3.85714286, 2.14285714,5.14285714, 2.85714286]

In [41]:
chisquare(obs,exp)

Power_divergenceResult(statistic=0.9333333396938274, pvalue=0.8173771570701455)

Since wind data has less chi square value then outlook data therefore outlook feature is important

# One-Way Annova

In [42]:
from scipy.stats import f_oneway

In [43]:
e = [2,4,2]
m = [2,3,4]
s = [1,2,5]

In [45]:
stat, p_value=f_oneway(e,m,s)

In [46]:
alpha=0.05

In [47]:
if(p_value<alpha):
    print("Reject the null hypothesis")
else:
    print("We failed to reject the null hypothesis")

We failed to reject the null hypothesis


In [48]:
performance1=[89,89,88,78,79]
performance2=[93,92,94,89,88]
performance3=[89,88,89,93,90]
performance4=[81,78,81,92,82]

In [50]:
stat,p_value=f_oneway(performance1,performance2,performance3,performance4)

In [51]:
if(p_value<alpha):
    print("Reject the null hypothesis")
else:
    print("We fail to reject the null hypothesis")

Reject the null hypothesis


# 2-Way Annova Test

In [55]:
import numpy as np
import pandas as pd
import statsmodels.api as sm #Run 2-Way Annova test
from statsmodels.formula.api import ols

Test whether plant growth is affected by fertilizers ad watering frequency

In [54]:
#Creating a dataframe
dataframe= pd.DataFrame({'Fertilizer':np.repeat(['daily','weekly'],15),
                        'Watering':np.repeat(['daily','weekly'],15),
                        'height':[14,16,15,15,16,13,12,11,14,
                                 15,16,16,17,18,14,13,14,14,
                                 14,15,16,16,17,28,14,13,14,
                                 14,14,15]})

In [56]:
dataframe

Fertilizer Watering  height
0       daily    daily      14
1       daily    daily      16
2       daily    daily      15
3       daily    daily      15
4       daily    daily      16
5       daily    daily      13
6       daily    daily      12
7       daily    daily      11
8       daily    daily      14
9       daily    daily      15
10      daily    daily      16
11      daily    daily      16
12      daily    daily      17
13      daily    daily      18
14      daily    daily      14
15     weekly   weekly      13
16     weekly   weekly      14
17     weekly   weekly      14
18     weekly   weekly      14
19     weekly   weekly      15
20     weekly   weekly      16
21     weekly   weekly      16
22     weekly   weekly      17
23     weekly   weekly      28
24     weekly   weekly      14
25     weekly   weekly      13
26     weekly   weekly      14
27     weekly   weekly      14
28     weekly   weekly      14
29     weekly   weekly      15

In [60]:
model = ols('height~ Fertilizer + Watering + Fertilizer:Watering',dataframe).fit()

In [63]:
#lm: Linear Regression model
result= sm.stats.anova_lm(model,type = 2)

In [64]:
result

df      sum_sq   mean_sq         F    PR(>F)
Fertilizer            1.0    2.700000  2.700000  0.320339  0.575912
Watering              1.0    1.989041  1.989041  0.235988  0.630899
Fertilizer:Watering   1.0    0.098425  0.098425  0.011678  0.914717
Residual             28.0  236.000000  8.428571       NaN       NaN

Since p_value> alpha(0.05), therefore Watering, Fertilizer, Fertilizer: Watering do not have a significant impact on height of a plant