### Introduction to Arrays

In [1]:
#pip : python package manager
import numpy as np

In [2]:
np

<module 'numpy' from '/Users/ritikagupta/anaconda3/lib/python3.11/site-packages/numpy/__init__.py'>

In [3]:
# Creating a list
lst = [1,2,3]

In [5]:
type(lst)

list

In [6]:
# Converting list into array
arr = np.array(lst)

In [7]:
arr

array([1, 2, 3])

In [8]:
type(arr) # n-dimensional array

numpy.ndarray

In [9]:
# Checking the dimension of array
arr.ndim

1

In [14]:
lst2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [15]:
arr2 = np.array(lst2)

In [17]:
arr2.ndim

2

In [18]:
arr2.shape # no of rows and no of columns

(3, 3)

In [19]:
arr2.size # Tells no. of elements in the array

9

In [20]:
arr2.dtype # Data type of array

dtype('int64')

In [21]:
# Creating an array of shape 3,5
zeros = np.zeros((3,5))

In [22]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
ones = np.ones((6,3))

In [24]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Reshape and Random Number Generator

In [25]:
# Generating random numbers
# An array of size 3*3
# Range : 0 to 1
np.random.random((3,3))

array([[0.49698721, 0.18745982, 0.50736219],
       [0.08091108, 0.52434463, 0.71076982],
       [0.43486865, 0.92771014, 0.66501452]])

In [26]:
if np.random.random() > 0.5:
    print("Run the function")
else:
    print("Don't run the function")


Don't run the function


In [28]:
# Generating numbers in a particular sequence
np.arange(1,10,3) # 1:starting value, 10 : ending value+1,  3 : Diff btw 2 values

array([1, 4, 7])

In [30]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
np.linspace(1,7,10) # return 10 values we want btw 1 & 7
# All values should be equidistant from each other

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [32]:
arr3 = np.random.random((4,3))
arr3

array([[0.28167747, 0.49305819, 0.26440924],
       [0.13990376, 0.80279618, 0.0793476 ],
       [0.79980237, 0.12679122, 0.2333444 ],
       [0.87558946, 0.29569776, 0.26440588]])

#### While reshaping an array , initial size of array = final size of array

In [36]:
arr3 = np.reshape(arr3,(3,4))
arr3

array([[0.28167747, 0.49305819, 0.26440924, 0.13990376],
       [0.80279618, 0.0793476 , 0.79980237, 0.12679122],
       [0.2333444 , 0.87558946, 0.29569776, 0.26440588]])

In [37]:
arr3 = np.reshape(arr3,(6,2)) 
arr3

array([[0.28167747, 0.49305819],
       [0.26440924, 0.13990376],
       [0.80279618, 0.0793476 ],
       [0.79980237, 0.12679122],
       [0.2333444 , 0.87558946],
       [0.29569776, 0.26440588]])

#### Flatten

In [41]:
# Converting into 1-D array
arr3 = arr3.flatten()
arr3

array([0.28167747, 0.49305819, 0.26440924, 0.13990376, 0.80279618,
       0.0793476 , 0.79980237, 0.12679122, 0.2333444 , 0.87558946,
       0.29569776, 0.26440588])

In [40]:
arr3.ndim

1

### Performing Arithmetic Operations in an Array

In [42]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [47]:
# Adding elements to an array
print(arr + 1)
print(arr - 1)
print(arr * 5)
print(arr / 2)
print(arr ** 2) # Squaring elements in array

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 5 10 15 20 25 30]
[0.5 1.  1.5 2.  2.5 3. ]
[ 1  4  9 16 25 36]


In [51]:
arr += 1
print(arr)
arr *= 2 # every time the array is getting updated
print(arr)

[3 4 5 6 7 8]
[ 6  8 10 12 14 16]


In [52]:
# Finding maximum element of an array
arr.max()

16

In [53]:
# Finding minimum element of an array
arr.min()

6

In [55]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
# Finding maximum element of an array row-wise and column-wise
# Returning max element in each column
arr.max(axis=0)

array([7, 8, 9])

In [58]:
# Returning max element in each row
arr.max(axis=1)

array([3, 6, 9])

In [59]:
# Returning min element in each column
arr.min(axis=0)

array([1, 2, 3])

In [60]:
# Returning min element in each row
arr.min(axis=1)

array([1, 4, 7])

In [61]:
# Finding sum of all elements in array
arr.sum()

45

### Performing Arithmetic Operation on Multiple Arrays

In [66]:
arr1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

arr2 = np.array([[9,8,7],
                [6,5,4],
                [3,2,1]])

arr3 = np.array([[9,8,7,1],
                [6,5,4,7],
                [3,2,1,5]])

In [67]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [69]:
# Adding 2 arrays
# Both arrays should be of same shape
arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [71]:
# Finding Dot Product of 2 arrays
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [72]:
arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

### Indexing in an array

In [73]:
arr = np.array([1,2,3,4,5])

In [74]:
# Accessing all elements of an array
arr[:]

array([1, 2, 3, 4, 5])

In [75]:
arr[:3]

array([1, 2, 3])

In [76]:
arr[2:]

array([3, 4, 5])

In [77]:
# Returns elements except 1st and last 2 elements
arr[2:-2]

array([3])

In [80]:
arr1[:,:] # 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arr1[:,:1] # Returns 1st columns all elements of 1st row

array([[1],
       [4],
       [7]])

In [82]:
arr1[:1,] # Returns 1st row all columns

array([[1, 2, 3]])

In [84]:
arr1[:2,:] # Return all element of 1st 2 rows

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
# Returns all elements of 1st column
arr1[:,:1]

array([[1],
       [4],
       [7]])

In [86]:
# Returns all elements of 2nd column
arr1[:,1:2]

array([[2],
       [5],
       [8]])

In [87]:
# Print 5
arr1[1:2,1:2]

array([[5]])

In [88]:
# All rows except 1st row and all columns except 1st column
arr1[1:,1:]

array([[5, 6],
       [8, 9]])