### Array Sorting

In [3]:
import numpy as np
arr = np.array([[7,3,6,8,1],[8,7,6,2,3],[9,3,4,5,6]])

In [4]:
arr

array([[7, 3, 6, 8, 1],
       [8, 7, 6, 2, 3],
       [9, 3, 4, 5, 6]])

In [5]:
# axis = 1 sort array row-wise  
np.sort(arr,axis=1,kind='mergesort')

array([[1, 3, 6, 7, 8],
       [2, 3, 6, 7, 8],
       [3, 4, 5, 6, 9]])

In [6]:
# axis = 0 sort array column-wise
np.sort(arr,axis=0,kind='mergesort')

array([[7, 3, 4, 2, 1],
       [8, 3, 6, 5, 3],
       [9, 7, 6, 8, 6]])

In [7]:
np.sort(arr,kind='mergesort') # When axis is not defined it sorts element row-wise

array([[1, 3, 6, 7, 8],
       [2, 3, 6, 7, 8],
       [3, 4, 5, 6, 9]])

### Array Merging
Stack : Concatenating different numpy arrays

In [8]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[8,7,6,5],[4,3,2,1]])

In [9]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

#### v-stack : concatenate two arrays vertically

In [12]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [13]:
np.vstack((arr2,arr1))

array([[8, 7, 6, 5],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

#### hstack : concatenate two arrays horizontally

In [15]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [17]:
np.hstack((arr2,arr1))

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

In [21]:
# axis = 0 : perform vertical stack 
arr = np.concatenate((arr1,arr2),axis=0)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [19]:
# axis = 1 : perform horizontal stack 
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

#### Splitting an array

In [24]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [23]:
# Horizontal split
np.hsplit(arr,2)

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]),
 array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [25]:
# Vertical split
np.vsplit(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]

### Array Slicing : DAP

In [28]:
arr = np.array([1,2,3,4,5,6,7,8])

In [29]:
arr[3]

4

In [30]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
arr[1:5] 

array([2, 3, 4, 5])

In [33]:
arr[3:] # Remove 1st 3 elements

array([4, 5, 6, 7, 8])

In [34]:
arr[:-3] # Remove last 3 elements

array([1, 2, 3, 4, 5])

In [35]:
arr[3:-3] # Remove 1st and last 3 elements

array([4, 5])

In [39]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [40]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [41]:
arr[:,:] # Boundary condn for rows , Boundary condn for columns

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [42]:
arr[:1,:] # Accesing 1st row

array([[1, 2, 3, 4]])

In [43]:
arr[:2,] # Accessing 1st 2 rows

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
arr[1:,:] #Return all rows except 1st row

array([[5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [47]:
arr[2,:]

array([8, 7, 6, 5])

In [48]:
arr[1:,1:] # Return all column except 1st

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])

In [49]:
arr[1:,1:2]

array([[6],
       [7],
       [3]])

In [50]:
arr[2,2] # 2nd row 2nd column element

6

In [52]:
arr[3,1] # 3rd row 3rd column

3

In [53]:
arr[1:,1:] # Removing 1st row and 1st column

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])

### Automating using Numpy

In [54]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [55]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [61]:
q = 0
# No of elements greater than 5
for i in lst:
    if(i>5):
        print(i)
        q += 1

print(q)

6
7
8
9
10
5


In [62]:
lst = np.array([1,2,3,4,5,6,7,8,9,10])

In [63]:
lst

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
print(lst[lst>5]) # Print all elements in array greater than 5

[ 6  7  8  9 10]


In [67]:
print(len(lst[lst>5]))

5


In [74]:
# Check no.of elements divisible by 3
print(lst[lst%3==0])
print(len(lst[lst%3==0]))

[3 6 9]
3
